# Site settings
name: "GreenShares"
title: "GreenShares: rendi ogni tuo acquisto su Amazon una donazione"
description: "Ogni acquisto effettuato su Amazon tramite GreenShares genererà una commissione che verrà devoluta interamente in beneficenza. Scopri come."
image:
  path: assets/img/greenshares-preview-image.jpg
logo: assets/img/logo-greenshares.png

meta_author: Sprint Studio
author: Sprint Studio
email: greenshares@sprintstudio.co
url: https://greenshares.it

keywords: ""
facebook:
  publisher: greenshares.it

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/greenshares.it/
  - title: instagram
    url: https://www.instagram.com/greenshares/
  - title: linkedin
    url: https://www.linkedin.com/company/greenshares/

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
