# Site settings
name: "GreenShares"
title: "GreenShares: rendi ogni tuo acquisto su Amazon una donazione"
description: "Ogni acquisto effettuato su Amazon tramite GreenShares genererà una commissione che verrà devoluta interamente in beneficenza. Scopri come."
email: greenshares@sprintstudio.co
url: https://greenshares.it
description: ""
keywords: ""
meta_author: Sprint Studio

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
    - title: twitter
      url: http://twitter.com/00taffe
